sudo: false

language: go

go:
  - "1.10.x"

git:
  depth: 1

notifications:
  email: false

before_install:
  - go get -u github.com/golang/dep/cmd/dep
  - dep ensure -v
  - go get -u github.com/alecthomas/gometalinter
  - gometalinter -i

script:
  - gometalinter --vendor -D gotype gotypex -E safesql -s vendor ./... --deadline=5m --no-config
  - go test -cover -race -v ./...